// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZMDT9TBG8qs28nRZ11OqMS0Xe69mv3mA',
    appId: '1:569332010269:web:4315a0bb950cea2f95a5f4',
    messagingSenderId: '569332010269',
    projectId: 'savemymoney',
    authDomain: 'savemymoney.firebaseapp.com',
    storageBucket: 'savemymoney.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDRzpr63P061PBalwF2CFVQuwd1ND5O4',
    appId: '1:569332010269:android:16b488c62d064e5f95a5f4',
    messagingSenderId: '569332010269',
    projectId: 'savemymoney',
    storageBucket: 'savemymoney.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMPlrJZAfFzOIc03hht1vObm7XOqUiGFQ',
    appId: '1:569332010269:ios:aab9bf7e952204a595a5f4',
    messagingSenderId: '569332010269',
    projectId: 'savemymoney',
    storageBucket: 'savemymoney.appspot.com',
    iosClientId: '569332010269-5g7uucr91c5ldk2sqvit9gepej6dr5om.apps.googleusercontent.com',
    iosBundleId: 'com.example.savemymoney',
  );
}
